services:
  - type: web
    name: my-bot-web
    runtime: python
    plan: free
    autoDeploy: true

    buildCommand: >
      pip install --upgrade pip setuptools wheel &&
      pip install -r requirements.txt

    startCommand: uvicorn 2025:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false